project:
  type: book

metadata-files:
  - _book-structure.yml

book:
  title: "IASI Dev User Guide"
  subtitle: "Herramientas de desarrollo y operación del ecosistema IASI"
  author: "IASI Project"

format:
  html:
    toc: true
    number-sections: true

  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true

execute:
  freeze: auto
