project:
  type: book

profile:
  default: html
  group:
    - [html, pdf, git]

metadata-files:
  - _book-structure.yml

book:
  title: "IASI Dev User Guide"
  subtitle: "Herramientas de desarrollo y operación del ecosistema IASI"
  author: "IASI Project"

format:
  html:
    toc: true
    number-sections: true

  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: false
    include-in-header: resources/tex/title-page.tex

execute:
  freeze: auto

filters:
  - iasi-plantuml
  - resources/lua/iasi-js.lua

filter-options:
  plantuml:
    enabled: true
    server: http://localhost:10025
    format: png
    cache: true
